const cities = {
  FR: [
    "Paris",
    "Lyon",
    "Marseille",
    "Bordeaux",
    "Nice",
    "Toulouse",
    "Strasbourg",
    "Nantes",
    "Montpellier",
    "Lille",
    "Rennes",
    "Reims",
    "Le Havre",
    "Saint-Étienne",
    "Toulon",
    "Grenoble",
    "Dijon",
    "Angers",
    "Nîmes",
    "Villeurbanne",
    "Saint-Denis",
    "Le Mans",
    "Aix-en-Provence",
    "Brest",
    "Tours",
    "Limoges",
    "Clermont-Ferrand",
    "Vitry-sur-Seine",
    "Metz",
    "Besançon",
    "Perpignan",
    "Orléans",
    "Mulhouse",
    "Caen",
    "Boulogne-Billancourt",
    "Rouen",
    "Nancy",
    "Argenteuil",
    "Montreuil",
    "Saint-Paul",
    "Saint-Denis",
    "Avignon",
    "Nanterre",
    "Poitiers",
    "Créteil",
    "Versailles",
    "Courbevoie",
    "Pau",
    "Colombes",
    "Asnières-sur-Seine",
    "Aulnay-sous-Bois",
    "Rueil-Malmaison",
    "La Rochelle",
    "Antibes",
    "Saint-Maur-des-Fossés",
    "Calais",
    "Chambéry",
    "Niort",
    "Vénissieux",
    "Beauvais",
    "Cannes",
    "Saint-Quentin",
    "Aubervilliers",
    "Neuilly-sur-Seine",
    "Pessac",
    "Valence",
    "Ivry-sur-Seine",
    "Cergy",
    "Villeneuve-d'Ascq",
    "Levallois-Perret",
    "Cholet",
    "Chelles",
    "Montauban",
    "La Seyne-sur-Mer",
    "Noisy-le-Grand",
    "Villejuif",
    "Vannes",
    "Sarcelles",
    "Lorient",
    "Maisons-Alfort",
    "Albi",
    "Fontenay-sous-Bois",
    "Meaux",
    "Bondy",
    "Châteauroux",
    "Chalon-sur-Saône",
    "Saint-Nazaire",
    "Charleville-Mézières",
    "Bastia",
    "Saint-Ouen",
    "Épinay-sur-Seine",
    "Roanne",
    "Saint-Brieuc",
    "Villepinte",
    "Agen",
    "Angoulême",
    "Thionville",
    "Dunkerque",
    "Cachan",
    "Saint-Cloud",
    "Alfortville",
    "Garges-lès-Gonesse",
    "Rodez",
    "Orly",
    "Châtillon",
    "Vincennes",
    "Vaulx-en-Velin",
    "Vitrolles",
    "Bagneux",
    "Le Perreux-sur-Marne",
    "Nevers",
    "Creil",
    "Montluçon",
    "Trappes",
    "Malakoff",
    "Les Sables-d'Olonne",
    "Plaisir",
    "Châtellerault",
    "Athis-Mons",
    "Haguenau",
    "Villeneuve-Saint-Georges",
    "Le Creusot",
    "Sainte-Geneviève-des-Bois",
    "Saint-Martin-d'Hères",
    "Conflans-Sainte-Honorine",
    "Pontoise",
    "Saint-Raphaël",
    "Neuilly-sur-Marne",
    "Vierzon",
    "Savigny-sur-Orge",
    "Saint-Laurent-du-Var",
    "Villeneuve-la-Garenne",
    "Villiers-sur-Marne",
    "Les Mureaux",
    "Le Chesnay",
    "La Courneuve",
    "Sotteville-lès-Rouen",
    "Vigneux-sur-Seine",
    "Les Ulis",
    "Thouars",
    "Villiers-le-Bel",
    "Villeneuve-sur-Lot",
    "Vitry-le-François",
    "Viry-Châtillon",
    "Vitry-sur-Orne",
    "Villeneuve-le-Roi",
    "Villeneuve-sur-Yonne",
    "Villeneuve-Tolosane",
    "Villeneuve-Saint-Georges",
    "Villeneuve-la-Garenne",
    "Villeneuve-d'Ascq",
    "Villeneuve-sur-Lot",
    "Villeneuve-le-Roi",
    "Villeneuve-sur-Yonne",
    "Villeneuve-Tolosane",
    "Villeneuve-Saint-Georges",
    "Villeneuve-la-Garenne",
    "Villeneuve-d'Ascq",
    "Villeneuve-sur-Lot",
    "Villeneuve-le-Roi",
    "Villeneuve-sur-Yonne",
    "Villeneuve-Tolosane",
    "Villeneuve-Saint-Georges",
    "Villeneuve-la-Garenne"
  ],
  US: [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "San Francisco",
    "Indianapolis",
    "Columbus",
    "Fort Worth",
    "Charlotte",
    "Seattle",
    "Denver",
    "El Paso",
    "Detroit",
    "Washington",
    "Boston",
    "Memphis",
    "Nashville",
    "Portland",
    "Oklahoma City",
    "Las Vegas",
    "Baltimore",
    "Louisville",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Mesa",
    "Kansas City",
    "Atlanta",
    "Long Beach",
    "Colorado Springs",
    "Raleigh",
    "Miami",
    "Virginia Beach",
    "Omaha",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Arlington",
    "New Orleans",
    "Wichita"
  ],
  ES: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Zaragoza",
    "Malaga",
    "Murcia",
    "Palma",
    "Las Palmas",
    "Bilbao",
    "Alicante",
    "Córdoba",
    "Valladolid",
    "Vigo",
    "Gijón",
    "L'Hospitalet",
    "La Coruña",
    "Granada",
    "Vitoria",
    "Elche",
    "Oviedo",
    "Badalona",
    "Cartagena",
    "Terrassa",
    "Jerez",
    "Sabadell",
    "Santa Cruz",
    "Albacete",
    "Castellón",
    "Alcorcón",
    "San Cristóbal",
    "Burgos",
    "Almería",
    "Santander",
    "Fuenlabrada",
    "Logroño",
    "Badajoz",
    "Salamanca",
    "Huelva",
    "Marbella",
    "Lérida",
    "Tarragona",
    "León",
    "Cádiz",
    "Jaén",
    "Ourense",
    "Mataró",
    "Algeciras",
    "Nueva San Salvador",
    "Nueva Carteya",
    "Cáceres",
    "Lugo",
    "Girona",
    "Pontevedra",
    "Toledo"
  ],
  DE: [
    "Berlin",
    "Hamburg",
    "Munich",
    "Cologne",
    "Frankfurt",
    "Stuttgart",
    "Düsseldorf",
    "Dortmund",
    "Essen",
    "Leipzig",
    "Bremen",
    "Dresden",
    "Hanover",
    "Nuremberg",
    "Duisburg",
    "Bochum",
    "Wuppertal",
    "Bielefeld",
    "Bonn",
    "Münster",
    "Karlsruhe",
    "Mannheim",
    "Augsburg",
    "Wiesbaden",
    "Gelsenkirchen",
    "Mönchengladbach",
    "Braunschweig",
    "Chemnitz",
    "Kiel",
    "Aachen",
    "Halle",
    "Magdeburg",
    "Freiburg",
    "Krefeld",
    "Lübeck",
    "Oberhausen",
    "Erfurt",
    "Mainz",
    "Rostock",
    "Kassel",
    "Hagen",
    "Hamm",
    "Saarbrücken",
    "Mülheim",
    "Herne",
    "Ludwigshafen",
    "Osnabrück",
    "Oldenburg",
    "Leverkusen",
    "Solingen",
    "Potsdam",
    "Neuss",
    "Heidelberg",
    "Paderborn",
    "Darmstadt",
    "Regensburg",
    "Ingolstadt",
    "Würzburg"
  ],
  IT: [
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    "Palermo",
    "Genoa",
    "Bologna",
    "Florence",
    "Venice",
    "Bari",
    "Catania",
    "Verona",
    "Messina",
    "Padua",
    "Trieste",
    "Brescia",
    "Prato",
    "Taranto",
    "Reggio Calabria",
    "Modena",
    "Livorno",
    "Cagliari",
    "Mestre",
    "Parma",
    "Foggia",
    "Reggio Emilia",
    "Salerno",
    "Ravenna",
    "Ferrara",
    "Rimini",
    "Siracusa",
    "Sassari",
    "Monza",
    "Pescara",
    "Bergamo",
    "Forlì",
    "Latina",
    "Vicenza",
    "Terni",
    "Bolzano",
    "Novara",
    "Ancona",
    "Andria",
    "Udine"
  ],
  GB: [
    "London",
    "Birmingham",
    "Manchester",
    "Glasgow",
    "Liverpool",
    "Edinburgh",
    "Leeds",
    "Bristol",
    "Sheffield",
    "Newcastle",
    "Cardiff",
    "Belfast",
    "Nottingham",
    "Southampton",
    "Leicester",
    "Brighton",
    "Hull",
    "Plymouth",
    "Stoke-on-Trent",
    "Wolverhampton",
    "Derby",
    "Swansea",
    "Southend-on-Sea",
    "Sunderland",
    "Walsall",
    "Middlesbrough",
    "Peterborough",
    "Oxford",
    "Slough",
    "York",
    "Poole",
    "Huddersfield",
    "Ipswich",
    "Telford",
    "Cambridge",
    "Doncaster",
    "Blackpool",
    "Watford",
    "Rotherham",
    "Newport",
    "Exeter",
    "Eastbourne",
    "Colchester",
    "Crawley",
    "Sutton Coldfield",
    "Blackburn",
    "Oldham",
    "Woking",
    "Cheltenham",
    "Chelmsford",
    "St Albans",
    "Basildon",
    "Grays",
    "Basingstoke",
    "Solihull",
    "Harlow",
    "Worcester",
    "Hemel Hempstead",
    "Chesterfield",
    "Maidstone",
    "Darlington",
    "Bedford"
  ],
  IN: [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Ahmedabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Jaipur",
    "Surat",
    "Lucknow",
    "Kanpur",
    "Nagpur",
    "Indore",
    "Thane",
    "Bhopal",
    "Visakhapatnam",
    "Pimpri-Chinchwad",
    "Patna",
    "Vadodara",
    "Ghaziabad",
    "Ludhiana",
    "New Delhi",
    "Agra"
  ],
  CN: [
    "Shanghai",
    "Beijing",
    "Chongqing",
    "Tianjin",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Nanjing",
    "Wuhan",
    "Hangzhou",
    "Xi'an",
    "Shenyang",
    "Harbin",
    "Suzhou",
    "Qingdao",
    "Dalian",
    "Zhengzhou",
    "Shantou",
    "Jinan",
    "Kunming",
    "Changchun",
    "Nanchang",
    "Fuzhou",
    "Wenzhou",
    "Changsha",
    "Hefei"
  ],
  RU: [
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Nizhny Novgorod",
    "Kazan",
    "Chelyabinsk",
    "Omsk",
    "Samara",
    "Rostov-on-Don",
    "Ufa",
    "Krasnoyarsk",
    "Perm",
    "Voronezh",
    "Volgograd",
    "Saratov",
    "Krasnodar",
    "Tolyatti",
    "Izhevsk",
    "Barnaul",
    "Ulyanovsk",
    "Tyumen",
    "Tomsk",
    "Orenburg",
    "Kemerovo",
    "Novokuznetsk",
    "Ryazan",
    "Astrakhan",
    "Naberezhnye Chelny",
    "Penza",
    "Lipetsk",
    "Tula",
    "Kirov",
    "Cheboksary",
    "Kaliningrad",
    "Bryansk"
  ],
  BR: [
    "São Paulo",
    "Rio de Janeiro",
    "Brasília",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
    "Manaus",
    "Curitiba",
    "Recife",
    "Goiânia",
    "Belém",
    "Porto Alegre",
    "São Luís",
    "Guarulhos",
    "Campinas",
    "Nova Iguaçu",
    "São Gonçalo",
    "Santo André",
    "Teresina",
    "Duque de Caxias",
    "Natal",
    "Campo Grande",
    "Jaboatão dos Guararapes",
    "Osasco",
    "São Bernardo do Campo",
    "Uberlândia",
    "Sorocaba",
    "Ribeirão Preto",
    "Cuiabá",
    "Feira de Santana",
    "Joinville",
    "Juiz de Fora",
    "Londrina",
    "Belford Roxo",
    "Niterói",
    "São João de Meriti",
    "Ananindeua",
    "Florianópolis",
    "Santos",
    "Ribeirão das Neves",
    "Vila Velha"
  ],
  PT: [
    "Lisbon",
    "Porto",
    "Vila Nova de Gaia",
    "Amadora",
    "Braga",
    "Funchal",
    "Coimbra",
    "Setúbal",
    "Almada",
    "Aveiro",
    "Rio Tinto",
    "Odivelas",
    "Viseu",
    "Leiria",
    "Ponta Delgada",
    "Faro",
    "Évora",
    "Guarda",
    "Beja",
    "Bragança",
    "Castelo Branco",
    "Portalegre",
    "Santarém",
    "Viana do Castelo"
  ],
  NL: [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Tilburg",
    "Groningen",
    "Almere",
    "Breda",
    "Nijmegen",
    "Enschede",
    "Haarlem",
    "Arnhem",
    "Zaanstad",
    "Amersfoort",
    "Apeldoorn",
    "Zwolle",
    "Maastricht",
    "Dordrecht",
    "Leiden",
    "Haarlemmermeer",
    "Emmen",
    "Westland",
    "Alkmaar",
    "Delft",
    "Venlo",
    "Deventer",
    "Sittard",
    "Helmond",
    "Heerlen",
    "Hilversum",
    "Oss",
    "Amstelveen",
    "Hoorn",
    "Vlaardingen",
    "Gouda",
    "Purmerend",
    "Roosendaal",
    "Oosterhout",
    "Veenendaal",
    "Zeist",
    "Hengelo"
  ],
  DNK: [
    "Copenhagen",
    "Aarhus",
    "Odense",
    "Aalborg",
    "Esbjerg",
    "Randers",
    "Kolding",
    "Horsens",
    "Vejle",
    "Roskilde",
    "Herning",
    "Helsingør",
    "Silkeborg",
    "Næstved",
    "Fredericia",
    "Hillerød",
    "Helsingborg",
    "Sønderborg",
    "Holstebro",
    "Taastrup",
    "Slagelse",
    "Frederikshavn",
    "Nørresundby",
    "Kalundborg",
    "Korsør",
    "Ringsted",
    "Nyborg",
    "Ikast",
    "Haderslev",
    "Skive",
    "Glostrup"
  ],
  SE: [
    "Stockholm",
    "Gothenburg",
    "Malmö",
    "Uppsala",
    "Västerås",
    "Örebro",
    "Linköping",
    "Helsingborg",
    "Jönköping",
    "Norrköping",
    "Lund",
    "Umeå",
    "Gävle",
    "Borås",
    "Södertälje",
    "Eskilstuna",
    "Halmstad",
    "Växjö",
    "Karlstad",
    "Trollhättan",
    "Luleå",
    "Östersund",
    "Borlänge",
    "Tumba",
    "Kristianstad",
    "Kalmar",
    "Falun",
    "Skövde"
  ],
  BE: [
    "Brussels",
    "Antwerp",
    "Ghent",
    "Charleroi",
    "Liège",
    "Bruges",
    "Namur",
    "Leuven",
    "Mons",
    "Aalst",
    "Mechelen",
    "La Louvière",
    "Kortrijk",
    "Hasselt",
    "Ostend",
    "Sint-Niklaas"
  ],
  FI: [
    "Helsinki",
    "Espoo",
    "Tampere",
    "Vantaa",
    "Oulu",
    "Turku",
    "Jyväskylä",
    "Lahti",
    "Kuopio",
    "Kouvola",
    "Pori",
    "Joensuu",
    "Lappeenranta",
    "Hämeenlinna",
    "Vaasa",
    "Seinäjoki",
    "Rovaniemi",
    "Mikkeli",
    "Salo",
    "Kotka"
  ],
  NO: [
    "Oslo",
    "Bergen",
    "Stavanger",
    "Trondheim",
    "Drammen",
    "Fredrikstad",
    "Skien",
    "Kristiansand",
    "Ålesund",
    "Tønsberg",
    "Moss",
    "Haugesund",
    "Sandnes",
    "Arendal",
    "Sarpsborg",
    "Bodø",
    "Porsgrunn",
    "Ås",
    "Hamar",
    "Kongsberg",
    "Larvik",
    "Halden",
    "Harstad",
    "Lillehammer",
    "Molde",
    "Gjøvik",
    "Askøy",
    "Kristiansund",
    "Narvik",
    "Lillestrøm",
    "Horten",
    "Elverum",
    "Moss",
    "Mo i Rana",
    "Nesoddtangen",
    "Jessheim",
    "Grimstad",
    "Kongsvinger",
    "Råholt",
    "Hønefoss",
    "Mysen",
    "Haugesund",
    "Sandefjord",
    "Førde",
    "Flekkefjord",
    "Kopervik",
    "Sogndal",
    "Stjørdalshalsen",
    "Vennesla",
    "Brumunddal"
  ],
  CH: [
    "Zürich",
    "Geneva",
    "Basel",
    "Lausanne",
    "Bern",
    "Winterthur",
    "Lucerne",
    "St. Gallen",
    "Lugano",
    "Biel",
    "Thun",
    "Köniz",
    "La Chaux-de-Fonds",
    "Schaffhausen",
    "Fribourg",
    "Chur",
    "Neuchâtel",
    "Uster",
    "Sion",
    "Yverdon-les-Bains",
    "Emmen",
    "Zug",
    "Kriens",
    "Rapperswil-Jona",
    "Dübendorf",
    "Dietikon",
    "Montreux",
    "Frauenfeld",
    "Wetzikon",
    "Wil",
    "Baar",
    "Meyrin",
    "Bulle",
    "Carouge",
    "Renens",
    "Kreuzlingen",
    "Pully",
    "Nyon",
    "Vevey",
    "Belp",
    "Binningen",
    "Gossau",
    "Allschwil",
    "Oberwil",
    "Thalwil",
    "Adliswil",
    "Regensdorf",
    "Opfikon",
    "Wädenswil",
    "Horgen",
    "Muri bei Bern",
    "Wohlen",
    "Birsfelden",
    "Muttenz",
    "Pratteln",
    "Möhlin",
    "Rheinfelden",
    "Spreitenbach",
    "Brugg",
    "Baden",
    "Wettingen",
    "Aarau",
    "Olten",
    "Solothurn",
    "Bellinzona",
    "Locarno",
    "Ascona"
  ],
  AU: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Gold Coast",
    "Newcastle",
    "Canberra",
    "Wollongong",
    "Sunshine Coast",
    "Hobart",
    "Geelong",
    "Townsville",
    "Cairns",
    "Darwin",
    "Toowoomba",
    "Ballarat",
    "Bendigo",
    "Albury",
    "Launceston",
    "Mackay",
    "Rockhampton",
    "Bunbury",
    "Coffs Harbour",
    "Bundaberg",
    "Wagga Wagga",
    "Hervey Bay",
    "Mildura",
    "Shepparton",
    "Port Macquarie",
    "Gladstone",
    "Tamworth",
    "Traralgon",
    "Orange"
  ],
  NZ: [
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Tauranga",
    "Lower Hutt",
    "Dunedin",
    "Palmerston North",
    "Napier",
    "Hastings",
    "Nelson",
    "Rotorua",
    "New Plymouth",
    "Whangarei",
    "Invercargill",
    "Wanganui",
    "Gisborne",
    "Masterton",
    "Levin",
    "Tokoroa",
    "Ashburton",
    "Whakatane",
    "Cambridge",
    "Blenheim",
    "Kerikeri",
    "Taupo",
    "Thames",
    "Greymouth",
    "Hokitika",
    "Westport",
    "Waihi",
    "Paeroa",
    "Te Awamutu",
    "Morrinsville",
    "Putaruru",
    "Te Kuiti",
    "Turangi",
    "Waiuku",
    "Warkworth",
    "Wellsford",
    "Whitianga",
    "Katikati",
    "Omokoroa",
    "Papamoa",
    "Pukekohe",
    "Tairua",
    "Tauranga",
    "Te Puke",
    "Thames",
    "Waihi",
    "Whangamata",
    "Whitianga"
  ],
  ZA: [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Bloemfontein",
    "East London",
    "Pietermaritzburg",
    "Benoni",
    "Tembisa",
    "Soweto",
    "Umlazi",
    "Vereeniging",
    "Bloemfontein",
    "Boksburg",
    "Welkom",
    "Newcastle",
    "Krugersdorp",
    "Diepsloot",
    "Randburg",
    "Brakpan",
    "Richards Bay",
    "Vanderbijlpark",
    "Centurion",
    "Roodepoort",
    "Paarl",
    "Springs",
    "Carletonville",
    "Klerksdorp",
    "Midrand",
    "Westonaria",
    "Middelburg",
    "Vryheid",
    "Orkney",
    "Kimberley",
    "eMbalenhle",
    "Nigel",
    "Mpumalanga",
    "Bisho",
    "Randfontein",
    "Witbank",
    "Mabopane",
    "Stellenbosch",
    "Ladysmith",
    "Richards Bay",
    "Grahamstown",
    "Kroonstad",
    "Uitenhage",
    "Thohoyandou",
    "Potchefstroom",
    "Brits",
    "Aliwal North",
    "Queenstown",
    "Vryburg",
    "Kroonstad",
    "Worcester",
    "Potchefstroom",
    "Brits",
    "Aliwal North",
    "Queenstown",
    "Vryburg",
    "Kroonstad",
    "Worcester",
    "Potchefstroom",
    "Brits",
    "Aliwal North",
    "Queenstown",
    "Vryburg",
    "Kroonstad",
    "Worcester",
    "Potchefstroom",
    "Brits",
    "Aliwal North",
    "Queenstown",
    "Vryburg",
    "Kroonstad",
    "Worcester",
    "Potchefstroom",
    "Brits",
    "Aliwal North"
  ],
  PL: [
    "Warsaw",
    "Kraków",
    "Łódź",
    "Wrocław",
    "Poznań",
    "Gdańsk",
    "Szczecin",
    "Bydgoszcz",
    "Lublin",
    "Białystok",
    "Katowice",
    "Gdynia",
    "Częstochowa",
    "Radom",
    "Sosnowiec",
    "Toruń",
    "Kielce",
    "Rzeszów",
    "Gliwice",
    "Zabrze",
    "Olsztyn",
    "Bielsko-Biała",
    "Bytom",
    "Zielona Góra",
    "Rybnik",
    "Ruda Śląska",
    "Tychy"
  ],
  JP: [
    "Tokyo",
    "Yokohama",
    "Osaka",
    "Nagoya",
    "Sapporo",
    "Fukuoka",
    "Kobe",
    "Kyoto",
    "Kawasaki",
    "Saitama",
    "Hiroshima",
    "Sendai",
    "Kitakyushu",
    "Chiba",
    "Sakai",
    "Niigata",
    "Hamamatsu",
    "Okayama",
    "Kumamoto",
    "Kagoshima",
    "Matsuyama",
    "Kochi",
    "Naha",
    "Nara",
    "Kurashiki",
    "Kanazawa",
    "Nagano",
    "Otsu",
    "Mito",
    "Fukui",
    "Tottori",
    "Matsue",
    "Wakayama",
    "Tokushima",
    "Kōchi",
    "Saitama",
    "Kumagaya",
    "Kawagoe",
    "Kasukabe",
    "Kuki",
    "Higashimatsuyama",
    "Kazo",
    "Fujimino",
    "Misato",
    "Koshigaya",
    "Soka",
    "Kawaguchi",
    "Toda",
    "Asaka",
    "Shiki",
    "Wako",
    "Niiza",
    "Iruma"
  ],
  KR: [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Suwon",
    "Ulsan",
    "Changwon",
    "Seongnam",
    "Goyang",
    "Yongin",
    "Bucheon",
    "Cheongju",
    "Ansan",
    "Jeonju",
    "Anyang",
    "Gimhae",
    "Gwangmyeong",
    "Hanam",
    "Hwaseong",
    "Icheon",
    "Iksan",
    "Jeju",
    "Jeongeup",
    "Jeonju",
    "Mokpo",
    "Namyangju",
    "Pohang",
    "Pyeongtaek",
    "Sejong",
    "Seosan",
    "Suncheon",
    "Uijeongbu",
    "Wonju",
    "Yangju",
    "Yangsan",
    "Yeosu",
    "Yongin"
  ],
  TW: [
    "Taipei",
    "New Taipei",
    "Taichung",
    "Kaohsiung",
    "Taoyuan",
    "Tainan",
    "Hsinchu",
    "Keelung",
    "Chiayi",
    "Changhua",
    "Pingtung",
    "Yilan",
    "Hualien",
    "Taitung",
    "Miaoli",
    "Nantou",
    "Penghu",
    "Kinmen",
    "Lienchiang"
  ],
  HK: [
    "Central and Western",
    "Eastern",
    "Southern",
    "Wan Chai",
    "Sham Shui Po",
    "Kowloon City",
    "Kwun Tong",
    "Wong Tai Sin",
    "Yau Tsim Mong",
    "Islands",
    "Kwai Tsing",
    "North",
    "Sai Kung",
    "Sha Tin",
    "Tai Po",
    "Tsuen Wan",
    "Tuen Mun",
    "Yuen Long"
  ],
  MO: [
    "Nossa Senhora de Fátima",
    "Santo António",
    "São Lázaro",
    "Sé",
    "Taipa",
    "Cotai",
    "Coloane",
    "Hac Sa",
    "Ilha Verde",
    "Lapa",
    "São Lourenço",
    "São Lázaro",
    "Santo António",
    "Sé",
    "Taipa",
    "Cotai",
    "Coloane",
    "Hac Sa",
    "Ilha Verde",
    "Lapa",
    "São Lourenço"
  ],
  VN: [
    "Hanoi",
    "Ho Chi Minh City",
    "Haiphong",
    "Da Nang",
    "Biên Hòa",
    "Nha Trang",
    "Hue",
    "Can Tho",
    "Vung Tau",
    "Buon Ma Thuot",
    "Hai Duong",
    "Hai Phong",
    "Hanoi",
    "Ho Chi Minh City",
    "Hue",
    "Long Xuyen",
    "My Tho",
    "Nam Dinh",
    "Nha Trang",
    "Phan Thiet",
    "Qui Nhon",
    "Rach Gia",
    "Thai Binh",
    "Thanh Hoa",
    "Vinh",
    "Vung Tau",
    "Yen Bai"
  ],
  TH: [
    "Bangkok",
    "Nonthaburi",
    "Nakhon Ratchasima",
    "Chiang Mai",
    "Hat Yai",
    "Udon Thani",
    "Pak Kret",
    "Khon Kaen",
    "Chaophraya Surasak",
    "Ubon Ratchathani",
    "Nakhon Si Thammarat",
    "Nakhon Pathom",
    "Phitsanulok",
    "Chiang Rai",
    "Samut Prakan",
    "Kanchanaburi",
    "Surat Thani",
    "Trang",
    "Phuket"
  ],
  MY: [
    "Kuala Lumpur",
    "George Town",
    "Ipoh",
    "Kuching",
    "Johor Bahru",
    "Kota Kinabalu",
    "Shah Alam",
    "Malacca City",
    "Alor Setar",
    "Kangar",
    "Kuala Terengganu",
    "Kota Bharu",
    "Seremban",
    "Putrajaya",
    "Labuan"
  ],
  SG: [
    "Bedok",
    "Bishan",
    "Bukit Batok",
    "Bukit Merah",
    "Bukit Panjang",
    "Bukit Timah",
    "Central Area",
    "Choa Chu Kang",
    "Clementi",
    "Geylang",
    "Hougang",
    "Jurong East",
    "Jurong West",
    "Kallang",
    "Marine Parade",
    "Novena",
    "Pasir Ris",
    "Punggol",
    "Queenstown",
    "Sembawang",
    "Sengkang",
    "Serangoon",
    "Tampines",
    "Toa Payoh",
    "Woodlands",
    "Yishun"
  ],
  AE: [
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Al Ain",
    "Ajman",
    "Ras Al Khaimah",
    "Fujairah",
    "Umm Al Quwain"
  ],
  SA: [
    "Riyadh",
    "Jeddah",
    "Mecca",
    "Medina",
    "Sulţānah",
    "Dammam",
    "Ta'if",
    "Tabuk",
    "Al Kharj",
    "Buraidah",
    "Khamis Mushait",
    "Al Hufūf",
    "Hafar Al-Batin",
    "Ha'il",
    "Najrān",
    "Al Jubayl",
    "Abha",
    "Yanbu",
    "Khobar",
    "Jizan",
    "Al Qatif",
    "Dhahran",
    "Al Mubarraz",
    "Hafar Al-Batin",
    "Al Khobar",
    "Al Hufūf",
    "Al Mubarraz",
    "Al Kharj",
    "Al Jubayl",
    "Al Qatif",
    "Abha",
    "Najrān",
    "Yanbu",
    "Khobar",
    "Jizan",
    "Dhahran",
    "Ta'if",
    "Tabuk",
    "Khamis Mushait",
    "Buraidah",
    "Ha'il",
    "Jeddah",
    "Mecca",
    "Medina",
    "Sulţānah",
    "Dammam"
  ],
  QA: [
    "Doha",
    "Al Wakrah",
    "Al Khor",
    "Ras Laffan Industrial City",
    "Mesaieed",
    "Al Rayyan",
    "Umm Salal",
    "Al Daayen",
    "Al Shamal",
    "Al Ruwais"
  ],
  KW: [
    "Kuwait City",
    "Al Ahmadi",
    "Hawalli",
    "As Salimiyah",
    "Sabah as Salim",
    "Al Farwaniyah",
    "Al Fahahil",
    "Ar Rumaythiyah",
    "Ar Riqqah",
    "Salwa"
  ],
  OM: [
    "Muscat",
    "Seeb",
    "Salalah",
    "Bawshar",
    "Sohar",
    "As Suwayq",
    "Ibri",
    "Saham",
    "Barka",
    "Rustaq",
    "Al Buraimi",
    "Nizwa",
    "Sur",
    "Bahla",
    "Izki",
    "Bidbid",
    "Khasab",
    "Adam",
    "Yanqul",
    "Al Khaburah",
    "Shinas",
    "Saiq",
    "Ibra",
    "Ibri",
    "Sohar",
    "As Suwayq",
    "Saham",
    "Barka",
    "Rustaq",
    "Al Buraimi",
    "Nizwa",
    "Sur",
    "Bahla",
    "Izki",
    "Bidbid",
    "Khasab",
    "Adam",
    "Yanqul",
    "Al Khaburah",
    "Shinas",
    "Saiq",
    "Ibra"
  ],
  BH: [
    "Manama",
    "Riffa",
    "Muharraq",
    "Hamad Town",
    "A'ali",
    "Isa Town",
    "Sitra",
    "Budaiya",
    "Jidhafs",
    "Al-Malikiyah",
    "Adliya",
    "Sanabis",
    "Tubli",
    "Juffair",
    "Zinj",
    "Hoora",
    "Gudaibiya",
    "Seef",
    "Qudaibiya",
    "Zinj",
    "Hoora",
    "Gudaibiya",
    "Seef",
    "Qudaibiya",
    "Zinj",
    "Hoora",
    "Gudaibiya",
    "Seef",
    "Qudaibiya"
  ],
  LB: [
    "Beirut",
    "Tripoli",
    "Sidon",
    "Tyre",
    "Jounieh",
    "Zahle",
    "Byblos",
    "Batroun",
    "Baalbek",
    "Chouf",
    "Aley"
  ],
  JO: [
    "Amman",
    "Zarqa",
    "Irbid",
    "Russeifa",
    "Wadi Al Seer",
    "Adjlun",
    "Aqaba",
    "Madaba",
    "As Salt",
    "Ar Ramtha",
    "Mafraq",
    "Al Jubayhah",
    "Sahab",
    "Al Quwaysimah",
    "Jarash",
    "At Tafil",
    "Ma'an",
    "Karak City",
    "Tafielah",
    "Safi"
  ],
  IL: [
    "Jerusalem",
    "Tel Aviv",
    "Haifa",
    "Rishon LeZion",
    "Petah Tikva",
    "Ashdod",
    "Netanya",
    "Beersheba",
    "Holon",
    "Bnei Brak",
    "Ramat Gan",
    "Bat Yam",
    "Ashkelon",
    "Herzliya",
    "Kfar Saba",
    "Ra'anana",
    "Lod",
    "Ramla",
    "Nahariya",
    "Modi'in",
    "Hadera",
    "Bet Shemesh",
    "Lod",
    "Ramla",
    "Nahariya",
    "Modi'in",
    "Hadera",
    "Bet Shemesh",
    "Lod",
    "Ramla",
    "Nahariya",
    "Modi'in",
    "Hadera",
    "Bet Shemesh",
    "Lod",
    "Ramla",
    "Nahariya",
    "Modi'in",
    "Hadera",
    "Bet Shemesh",
    "Lod",
    "Ramla",
    "Nahariya",
    "Modi'in",
    "Hadera",
    "Bet Shemesh",
    "Lod",
    "Ramla",
    "Nahariya",
    "Modi'in",
    "Hadera",
    "Bet Shemesh"
  ],
  EG: [
    "Cairo",
    "Alexandria",
    "Giza",
    "Shubra El-Kheima",
    "Port Said",
    "Suez",
    "Luxor",
    "Mansoura",
    "El-Mahalla El-Kubra",
    "Tanta",
    "Asyut",
    "Ismailia",
    "Fayyum",
    "Zagazig",
    "Aswan",
    "Damietta",
    "Damanhur",
    "Al-Minya",
    "Beni Suef",
    "Hurghada",
    "Qena",
    "Sohag",
    "Shibin El Kom",
    "Banha",
    "Kafr El Sheikh",
    "Arish",
    "Mallawi",
    "10th of Ramadan City",
    "Bilbais",
    "Marsa Matruh",
    "Idfu",
    "Mit Ghamr",
    "Al-Hamidiyya",
    "Desouk",
    "Qalyub",
    "Abu Kabir",
    "Kafr El Dawwar",
    "Girga",
    "Akhmim",
    "Matareya",
    "Edko",
    "Basyoun",
    "Samalut",
    "Minyat an Nasr",
    "Al Fayyum",
    "Al Mansurah",
    "Al Minya",
    "Al Qusiyah",
    "Al Qusayr",
    "Al Tur",
    "Alamal",
    "Alamin",
    "Alarish"
  ],
  DZ: [
    "Algiers",
    "Oran",
    "Constantine",
    "Annaba",
    "Blida",
    "Batna",
    "Djelfa",
    "Sétif",
    "Sidi Bel Abbès",
    "Biskra",
    "Tébessa",
    "El Oued",
    "Skikda",
    "Tiaret",
    "Béjaïa",
    "Tlemcen",
    "Oum el Bouaghi",
    "Guelma",
    "Aïn Oussera",
    "Relizane",
    "Bordj Bou Arréridj",
    "Chlef",
    "Médéa",
    "Laghouat",
    "Aïn Beïda",
    "Baraki",
    "Bouïra",
    "M'Sila",
    "Khenchela",
    "El Eulma",
    "Rouïba",
    "Boumerdes",
    "Khemis Miliana",
    "Aïn Touta",
    "Aïn Taya",
    "Bir el Djir",
    "Aïn Fakroun",
    "Dar el Beïda",
    "Aïn Sefra",
    "Aïn el Bya",
    "Aïn el Melh",
    "Aïn el Turk",
    "Aïn el Hammam",
    "Aïn el Bell",
    "Aïn el Berd",
    "Aïn el Aouda",
    "Aïn el Hadjel",
    "Aïn el Hadjar",
    "Aïn el Arbaa",
    "Aïn el Arbi",
    "Aïn el Amara",
    "Aïn el Aioune",
    "Aïn el Aïssi",
    "Aïn el Assel",
    "Aïn el Assala",
    "Aïn el Assafir",
    "Aïn el Arba"
  ],
  MA: [
    "Casablanca",
    "Rabat",
    "Fès",
    "Salé",
    "Marrakesh",
    "Agadir",
    "Tangier",
    "Meknès",
    "Oujda",
    "Kenitra",
    "Tétouan",
    "Safi",
    "Mohammedia",
    "Khouribga",
    "El Jadida",
    "Beni Mellal",
    "Taza",
    "Nador",
    "Settat",
    "Témara",
    "Ksar El Kebir",
    "Larache",
    "Guelmim",
    "Khenifra",
    "Berrechid",
    "Taourirt",
    "Berkane",
    "Sidi Slimane",
    "Sidi Kacem",
    "Errachidia",
    "Oued Zem",
    "Fkih Ben Salah",
    "Tiflet",
    "Sefrou",
    "Youssoufia",
    "Lqliaa",
    "Taroudant",
    "Essaouira",
    "Oulad Teima",
    "Benslimane",
    "Midelt",
    "Azrou",
    "Skhirat",
    "Tinghir",
    "Ouarzazat",
    "Khemisset",
    "Boujniba",
    "Imzouren",
    "Tiznit",
    "Sidi Bennour",
    "Driouch",
    "Tahla",
    "Ouazzane",
    "Tafraout",
    "Sidi Yahia El Gharb",
    "Sidi Ifni",
    "Sidi Bennour",
    "Driouch",
    "Tahla",
    "Ouazzane",
    "Tafraout",
    "Sidi Yahia El Gharb",
    "Sidi Ifni",
    "Sidi Bennour",
    "Driouch",
    "Tahla",
    "Ouazzane",
    "Tafraout",
    "Sidi Yahia El Gharb",
    "Sidi Ifni",
    "Sidi Bennour",
    "Driouch",
    "Tahla",
    "Ouazzane"
  ],
  TN: [
    "Tunis",
    "Sfax",
    "Sousse",
    "Ettadhamen",
    "Kairouan",
    "Bizerte",
    "Gabès",
    "Ariana",
    "Gafsa",
    "El Mourouj",
    "Kasserine",
    "Rades",
    "La Goulette",
    "Zarzis",
    "Douane",
    "Hammam-Lif",
    "Oued Ellil",
    "La Mohammedia",
    "Menzel Bourguiba",
    "Zaghouan",
    "Téboulba",
    "Mateur",
    "Menzel Jemil",
    "Menzel Abderhaman",
    "Menzel Kamel",
    "Menzel Fersi",
    "Menzel Chaker",
    "Menzel Bouzelfa",
    "Menzel Beja",
    "Menzel Ben Cherif",
    "Menzel Abderrahmane",
    "Menzel Abderhaman"
  ],
  LY: [
    "Tripoli",
    "Benghazi",
    "Misratah",
    "Tarhuna",
    "Al Khums",
    "Zawiya",
    "Zliten",
    "Sabratah",
    "Al Ajaylat",
    "Gharyan",
    "Derna",
    "Tobruk",
    "Sirte",
    "Az Zawiyah",
    "Al Marj",
    "Zintan",
    "Al Khums",
    "Zawiya",
    "Zliten",
    "Sabratah",
    "Al Ajaylat",
    "Gharyan",
    "Derna",
    "Tobruk",
    "Sirte",
    "Az Zawiyah",
    "Al Marj",
    "Zintan",
    "Al Khums",
    "Zawiya",
    "Zliten",
    "Sabratah",
    "Al Ajaylat",
    "Gharyan",
    "Derna",
    "Tobruk",
    "Sirte",
    "Az Zawiyah",
    "Al Marj",
    "Zintan",
    "Al Khums",
    "Zawiya",
    "Zliten",
    "Sabratah",
    "Al Ajaylat",
    "Gharyan",
    "Derna",
    "Tobruk",
    "Sirte",
    "Az Zawiyah",
    "Al Marj",
    "Zintan"
  ],
  CM: [
    "Douala",
    "Yaoundé",
    "Bamenda",
    "Bafoussam",
    "Garoua",
    "Maroua",
    "Ngaoundéré",
    "Kumba",
    "Buea",
    "Nkongsamba",
    "Bertoua",
    "Ebolowa",
    "Loum",
    "Kribi",
    "Mbouda",
    "Dschang",
    "Foumban",
    "Edea",
    "Yagoua",
    "Meiganga",
    "Bafia",
    "Bafang",
    "Tiko",
    "Mora",
    "Kousséri",
    "Bangangté",
    "Foumbot",
    "Melong",
    "Mbalmayo",
    "Nkoteng",
    "Banyo",
    "Mokolo",
    "Guider",
    "Obala",
    "Mbandjok",
    "Muyuka",
    "Fontem",
    "Nanga Eboko",
    "Bogo"
  ],
  CZ: [
    "Prague",
    "Brno",
    "Ostrava",
    "Plzeň",
    "Liberec",
    "Olomouc",
    "Ústí nad Labem",
    "Hradec Králové",
    "České Budějovice",
    "Pardubice",
    "Havířov",
    "Zlín",
    "Kladno",
    "Most",
    "Karviná",
    "Opava",
    "Frýdek-Místek",
    "Děčín",
    "Karlovy Vary",
    "Teplice",
    "Chomutov",
    "Jihlava",
    "Prostějov",
    "Přerov",
    "Jablonec nad Nisou",
    "Mladá Boleslav",
    "Česká Lípa",
    "Třebíč",
    "Třinec",
    "Tábor",
    "Znojmo",
    "Příbram",
    "Orlová",
    "Cheb",
    "Kolín",
    "Trutnov",
    "Písek",
    "Kroměříž",
    "Šumperk",
    "Vsetín",
    "Litvínov",
    "Valašské Meziříčí",
    "Litoměřice",
    "Žďár nad Sázavou",
    "Hodonín",
    "Český Těšín",
    "Blansko",
    "Krnov",
    "Sokolov",
    "Vysoké Mýto",
    "Česká Třebová",
    "Jindřichův Hradec",
    "Český Krumlov",
    "Náchod",
    "Žatec",
    "Havlíčkův Brod",
    "Žďár nad Sázavou",
    "Hodonín",
    "Český Těšín",
    "Blansko",
    "Krnov",
    "Sokolov",
    "Vysoké Mýto"
  ],
  RO: [
    "Bucharest",
    "Cluj-Napoca",
    "Timișoara",
    "Iași",
    "Constanța",
    "Craiova",
    "Brașov",
    "Galați",
    "Ploiești",
    "Oradea",
    "Brăila",
    "Arad",
    "Pitești",
    "Sibiu",
    "Bacău",
    "Târgu Mureș",
    "Baia Mare",
    "Buzău",
    "Botoșani",
    "Satu Mare",
    "Râmnicu Vâlcea",
    "Drobeta-Turnu Severin",
    "Suceava",
    "Piatra Neamț",
    "Târgu Jiu",
    "Tulcea",
    "Târgoviște",
    "Reșița",
    "Focșani",
    "Bistrița",
    "Slatina",
    "Călărași",
    "Alba Iulia",
    "Giurgiu",
    "Deva",
    "Hunedoara",
    "Zalău",
    "Sfântu-Gheorghe",
    "Turda",
    "Medgidia",
    "Onești",
    "Miercurea-Ciuc",
    "Roman",
    "Buftea",
    "Petrila",
    "Câmpulung",
    "Câmpina",
    "Mangalia",
    "Rădăuți",
    "Odorheiu Secuiesc",
    "Moreni",
    "Gherla",
    "Oltenița"
  ],
  CA: [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec City",
    "Hamilton",
    "London",
    "Kitchener",
    "St. Catharines",
    "Halifax",
    "Oshawa",
    "Victoria",
    "Windsor",
    "Saskatoon",
    "Regina",
    "Sherbrooke",
    "St. John's",
    "Barrie",
    "Kelowna",
    "Abbotsford",
    "Greater Sudbury",
    "Kingston",
    "Guelph",
    "Moncton",
    "Brantford",
    "Saint John",
    "Thunder Bay",
    "Peterborough",
    "Red Deer",
    "Lethbridge"
  ],
  MX: [
    "Mexico City",
    "Ecatepec",
    "Guadalajara",
    "Puebla",
    "Juárez",
    "Tijuana",
    "León",
    "Zapopan",
    "Monterrey",
    "Nezahualcóyotl",
    "Mexicali",
    "Culiacán",
    "Naucalpan",
    "Mérida",
    "San Luis Potosí",
    "Aguascalientes",
    "Hermosillo",
    "Saltillo",
    "Naucalpan",
    "Mérida",
    "San Luis Potosí"
  ],
  PE: [
    "Lima",
    "Arequipa",
    "Callao",
    "Trujillo",
    "Chiclayo",
    "Iquitos",
    "Huancayo",
    "Piura",
    "Cusco",
    "Chimbote",
    "Pucallpa",
    "Tacna",
    "Ica",
    "Juliaca",
    "Sullana",
    "Chincha Alta",
    "Huanuco",
    "Ayacucho",
    "Cajamarca",
    "Puno",
    "Tumbes",
    "Talara",
    "Chulucanas",
    "Huaraz",
    "Cerro de Pasco",
    "Tingo Maria",
    "Chota",
    "Jaen",
    "Tarma",
    "Moyobamba",
    "Lambayeque",
    "Puerto Maldonado",
    "Huacho",
    "Yurimaguas",
    "Chachapoyas",
    "Paita",
    "Abancay",
    "Andahuaylas",
    "Moquegua",
    "Ilo",
    "Tarma",
    "Moyobamba",
    "Lambayeque",
    "Puerto Maldonado",
    "Huacho",
    "Yurimaguas",
    "Chachapoyas",
    "Paita",
    "Abancay",
    "Andahuaylas",
    "Moquegua",
    "Ilo",
    "Tarma",
    "Moyobamba",
    "Lambayeque",
    "Puerto Maldonado",
    "Huacho",
    "Yurimaguas",
    "Chachapoyas",
    "Paita",
    "Abancay",
    "Andahuaylas",
    "Moquegua",
    "Ilo"
  ],
  SK: [
    "Bratislava",
    "Košice",
    "Prešov",
    "Žilina",
    "Nitra",
    "Banská Bystrica",
    "Trnava",
    "Martin",
    "Trenčín",
    "Poprad",
    "Prievidza",
    "Zvolen",
    "Považská Bystrica",
    "Michalovce",
    "Spišská Nová Ves",
    "Komárno",
    "Levice",
    "Humenné",
    "Bardejov"
  ],
  SI: [
    "Ljubljana",
    "Maribor",
    "Celje",
    "Kranj",
    "Velenje",
    "Koper",
    "Novo Mesto",
    "Ptuj",
    "Trbovlje",
    "Kamnik",
    "Jesenice",
    "Nova Gorica",
    "Domžale",
    "Škofja Loka",
    "Izola",
    "Murska Sobota",
    "Krško",
    "Postojna",
    "Logatec",
    "Slovenj Gradec",
    "Črnomelj",
    "Metlika",
    "Brežice",
    "Grosuplje",
    "Sežana",
    "Rogaška Slatina",
    "Šentjur",
    "Lucija",
    "Hrastnik",
    "Bled",
    "Žalec",
    "Litija",
    "Brezovica"
  ]
  // Vous pouvez continuer à ajouter des pays et des villes selon vos besoins
};

export default cities;
