fragment EventFragment on Event {
  ...EventSnippetFragment
  cost
  lineup
  promoter
  description
  venue
  time {
    begin
    end
  }
  location {
    position
  }
  flyer {
    front
    back
  }
  links {
    event
    venue
  }
}
