fragment EventFragment on Event {
  _id
  slug
  title
  date
  endDate
  description
  country
  address
  flyer {
    front
  }
  cost
  lineup
  promoter
  description
  venue
  time {
    begin
    end
  }
  location {
    position
  }
  flyer {
    front
    back
  }
  links {
    event
    venue
  }
}
