fragment ReleaseFragment on ReleaseDtoOutput {
 _id
  slug
  title
  releaseDate
  role
  year
  thumb
  label
  tracklist {
    title
  }
  discogs
  bandcamp
  notes
  cat
  format
  role
  genre
  year
  tracklist {
    position
    id
    title
    artists {
      name
      role
    }
    stream {
      id
      title
      artwork
      uri
      url
      waveform
      duration
    }
  }
}

fragment ReleaseItemFragment on ReleaseItem {
  id
  name
  price
  availableQuantity
  release {
    ...ReleaseFragment
  }
}
