fragment ReleaseSnippetFragment on ReleaseDtoOutput {
  _id
  slug
  title
  releaseDate
  role
  year
  thumb
  label
  tracklist {
    title
  }
  discogs
  bandcamp
  notes
}

fragment ReleaseSnippetItemFragment on ReleaseItem {
  id
  name
  price
  availableQuantity
  release {
    ...ReleaseSnippetFragment
  }
}
