fragment ReleaseFragment on Release {
  ...ReleaseSnippetFragment
  notes
  cat
  format
  role
  genre
  tracklist {
    position
    id
    title
    artists {
      name
      role
    }
    stream {
      id
      title
      artwork
      uri
      url
      waveform
      duration
    }
  }
}
