fragment StripeIntentFragment on StripeResponse {
  status
  intent
}

fragment OrderStripeResponseFragment on OrderStripeResponse {
  order {
    ...OrderFragment
  }
  paymentIntent {
    ...StripeIntentFragment
  }
}
