fragment SummaryFragment on SummaryEntity {
  nextEvent {
    ...EventSnippetFragment
  }
  topPodcast {
    ...TrackSnippetFragment
  }
  latestPodcast {
    ...TrackSnippetFragment
  }
  latestReleases {
    ...ReleaseSnippetItemFragment
  }
  latestVideo {
    ...VideoFragment
  }
}
