fragment SummaryFragment on SummaryEntity {
  nextEvent {
    ...EventFragment
  }
  topPodcast {
    ...TrackFragment
  }
  latestPodcast {
    ...TrackFragment
  }
  latestReleases {
    ...ReleaseItemFragment
  }
  latestVideo {
    ...VideoFragment
  }
}
