fragment TrackFragment on Track {
  ...TrackSnippetFragment
  soundcloud
  download
  downloadable
  license
  stats {
    count
    downloads
  }
  taglist
  tracklist
  likes {
    id
    avatar
    userName
    soundcloud
    uri
  }
  comments {
    id
    createdAt
    body
    user {
      avatar
      userName
      soundcloud
      uri
    }
  }
}
