fragment TrackFragment on Track {
  id
  slug
  title
  genre
  description
  artwork
  date
  uri
  url
  duration
  waveform
  downloadable
  download
  soundcloud
  license
  stats {
    count
    downloads
  }
  taglist
  tracklist
  likes {
    id
    avatar
    userName
    soundcloud
    uri
  }
  comments {
    id
    createdAt
    body
    user {
      avatar
      userName
      soundcloud
      uri
    }
  }
}
