export default function Index() {
  return (
    <div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
      <div>PODCASTS</div>
    </div>
  );
}
