query CarrierPrices($profile: String!,$country: String!, $items: [CartItemInput!]!) {
  carrierPrices(profile: $profile, country: $country, items: $items) {
    upsPrice
    colissimoPrice
    mondialRelayPrice
  }
}
