fragment EventSnippetFragment on Event {
  _id
  date
  title
  date
  country
  address
  flyer {
    front
  }
}

query EventsQuery($profile: String!) {
  events(profile: $profile) {
    ...EventSnippetFragment
  }
}
