fragment InfosFragment on Infos {
  bio {
    content
  }
  instagram
  RA
  facebook
  twitter
  soundcloud
  discogs
  bookingDetails
}

query InfosQuery($profile: String!) {
  infos(profile: $profile) {
    ...InfosFragment
  }
}
