fragment ReleaseFragment on Release {
  ...ReleaseSnippetFragment
  notes
  tracklist {
    position
    stream {
      id
      artwork
      uri
      url
      waveform
      duration
    }
  }
}

query ReleaseQuery($profile: String!, $id: String!) {
  release(profile: $profile, id: $id) {
    ...ReleaseFragment
  }
}
